export const CHAMPLIST_REQUEST = 'CHAMPLIST_REQUEST';
export const CHAMPLIST_SUCCESS = 'CHAMPLIST_SUCCESS';
export const CHAMPLIST_FAILED = 'CHAMPLIST_FAILED';

export const VERSION_REQUEST = 'VERSION_REQUEST';
export const VERSION_SUCCESS = 'VERSION_SUCCESS';
export const VERSION_FAILED = 'VERSION_FAILED';