export const ADDCHAMP_REQUEST = 'ADDCHAMP_REQUEST';
export const ADDCHAMP_SUCCESS = 'ADDCHAMP_SUCCESS';
export const ADDCHAMP_FAILED = 'ADDCHAMP_FAILED';

export const DELETECHAMP_REQUEST = 'DELETECHAMP_REQUEST';
export const DELETECHAMP_SUCCESS = 'DELETECHAMP_SUCCESS';
export const DELETECHAMP_FAILED = 'DELETECHAMP_FAILED';